# Register at https://openweathermap.org to get your API key
api_key = "b2839e282f0a803887022e9ca51426e2"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "683506"

# Display settings
units = "metric"
display_symbol = "°C"
